Your New Favorite Poem/Pages/AddPoet.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Your_New_Favorite_Poem.Models;

namespace Your_New_Favorite_Poem.Pages
{
    public class AddPoetModel : PageModel
    {
        private readonly AuthorsDbContext _authorsDbContext;
        private readonly ILogger<AddPoetModel> _logger;

        public AddPoetModel(ILogger<AddPoetModel> logger, AuthorsDbContext authorsDbContext)
        {
            _logger = logger;
            _authorsDbContext = authorsDbContext;

        }


        public string SubmissionResult { get; private set; } = "Submit Poem";
        public async Task OnPostSubmit(string authorName, string poemUrl, string poemName, string bio, string pictureUrl, string pictureAltText)
        {
            var isPoemUrlValid = Uri.TryCreate(poemUrl, UriKind.Absolute, out var poemUri);
            var isPictureUrlValid = Uri.TryCreate(pictureUrl, UriKind.Absolute, out var pictureUri);
            if (!isPoemUrlValid || poemUri is null)
            {
                SubmissionResult = "Invalid Poem URL";
            }
            else if (!isPictureUrlValid || pictureUri is null)
            {
                SubmissionResult = "Invalid Picture URL";
            }
            else
            {
                try
                {
                    var givenAuthor = new Author
                    {
                        IsVerified = false,
                        PictureAltText = pictureAltText,
                        Bio = bio,
                        Name = authorName,
                        PictureURL = pictureUri,
                        Poems = new List<Poem>
                        {
                            new Poem()
                            {
                                URL = poemUri,
                                Title = poemName,
                                IsVerified = false
                            }
                        }

                    };

                    await _authorsDbContext.AddAsync<Author>(givenAuthor);
                    await _authorsDbContext.SaveChangesAsync();

                    SubmissionResult = "Submission Accepted";
                }
                catch
                {
                    SubmissionResult = "Database Error";
                }
            }
        }

        public void OnGet()
        {

        }
    }
}

Your New Favorite Poem/Pages/BurgerSecrets.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Your_New_Favorite_Poem.Pages
{
    public class BurgerSecretsModel : PageModel
    {
       
        public void OnGet()
        {
        }
    }
}

Your New Favorite Poem/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Your_New_Favorite_Poem.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; } = string.Empty;

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Your New Favorite Poem/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Your_New_Favorite_Poem.Models;

namespace Your_New_Favorite_Poem.Pages
{
    public class IndexModel : PageModel
    {
        public IReadOnlyList<Author> AuthorsFromDatabase { get; }
        public string Home { get; set; } = "Home";
        public IActionResult OnPostRandomPoem()
        {
            //random button not working
            var rnd = new Random();
            var index = rnd.Next(0, AuthorsFromDatabase.Count);

            var randomAuthor = AuthorsFromDatabase[index];
            var poemIndex = rnd.Next(0, randomAuthor.Poems.Count);

            return Redirect(randomAuthor.Poems[poemIndex].URL?.ToString());
        }
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, AuthorsDbContext authorsDbContext)
        {
            _logger = logger;
            _authorsDbContext = authorsDbContext;
            var temp = authorsDbContext.Poems.ToList();
            AuthorsFromDatabase = authorsDbContext.Authors.ToList();
            
        }
        private readonly AuthorsDbContext _authorsDbContext;
    }
}

Your New Favorite Poem/Pages/Poets.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Your_New_Favorite_Poem.Database;
using Your_New_Favorite_Poem.Models;
using System.Collections.Generic;
using System;
using System.Linq;

namespace Your_New_Favorite_Poem.Pages
{

    public class PoetsModel : PageModel
    {
        public IReadOnlyList<Author> AuthorsFromDatabase { get; private set; } = Array.Empty<Author>();
        readonly AuthorsDbContext _authorsDbContext;
        public PoetsModel(ILogger<PoetsModel> logger, AuthorsDbContext authorsDbContext)
        {
            Logger = logger;
            _authorsDbContext = authorsDbContext;
        }

        internal ILogger<PoetsModel> Logger { get; }

        public void OnGet()
        {
            AuthorsFromDatabase = _authorsDbContext.Authors.ToList();
        }
    }
}

Your New Favorite Poem/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Your_New_Favorite_Poem.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Your New Favorite Poem/Pages/Submission.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Your_New_Favorite_Poem.Pages
{
    public class SubmissionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Your New Favorite Poem/Pages/AddPoet.cshtml
@page
@model Your_New_Favorite_Poem.Pages.AddPoetModel
@{
    ViewData["Title"] = "Add a Poet";
}
<body>
    <section class="morphDiv">
        <h1 style="text-align:center;" > New Poem </h1>
        <form method="post" asp-page="AddPoet">
            <section class="PoemName">
                <label for="PoemName">Poem Title</label>
                <input type="text" name="poemName" id="poemName">
            </section>
            <section>
                <label for="AuthorName">Author</label>
                <input id="authorName" type="text" name="authorName">
            </section>
            <section class="PoemUrl">
                <label for="PoemUrl">Poem URL</label>
                <input type="text" name="poemUrl" id="poemUrl">
            </section>
            <section class="PictureUrl">
                <label for="PictureUrl">Image of Poet URL</label>
                <input type="text" name="pictureUrl" id="pictureUrl">
            </section>
            <section class="PictureAltText">
                <label for="PictureAltText">Picture Description</label>
                <input type="text" name="pictureAltText" id="pictureAltText">
            </section>
            <section class="Bio">
                <label for="Bio">Author Biography</label>
                <textarea type="text" name="bio" id="bio"></textarea>
            </section>
            <section>
                <input type="submit" value=@Model.SubmissionResult asp-page-handler="Submit" id="submission">
            </section>
        </form>
    </section>
</body>

Your New Favorite Poem/Pages/BurgerSecrets.cshtml
@page
@model Your_New_Favorite_Poem.Pages.BurgerSecretsModel
@{
   ViewData["Title"] = "Burger Secrets!";
}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <title>BURGER SECRETS</title>
</head>
<body>
    <section id="overlay">
        <img src="https://s3.amazonaws.com/codecademy-content/courses/web-101/unit-6/htmlcss1-img_burger-logo.svg" alt="Davie's Burgers Logo" id="logo">
        <hr>
        <form  method="post" asp-page="BurgerSecrets">
            <h1>Create a burger!</h1>
            <section class="protein">
                <label for="patty">What type of protein would you like?</label>
                <input type="text" name="patty" id="patty">
            </section>
            <hr>

            <section class="patties">
                <label for="amount">How many patties would you like?</label>
                <input type="number" name="amount" id="amount">
            </section>
            <hr>

            <section class="cooked">
                <label for="doneness">How do you want your patty cooked</label>
                <br>
                <span>Rare</span>
                <input type="range" name="doneness" id="doneness" value="3" min="1" max="5">
                <span>Well-Done</span>
            </section>
            <hr>

            <section class="toppings">
                <span>What toppings would you like?</span>
                <br>
                <input type="checkbox" name="topping" id="lettuce" value="lettuce">
                <label for="lettuce">Lettuce</label>
                <input type="checkbox" name="topping" id="tomato" value="tomato">
                <label for="tomato">Tomato</label>
                <input type="checkbox" name="topping" id="onion" value="onion">
                <label for="onion">Onion</label>
            </section>
            <hr>

            <section class="cheesy">
                <span>Would you like to add cheese?</span>
                <br>
                <input type="radio" name="cheese" id="yes" value="yes">
                <label for="yes">Yes</label>
                <input type="radio" name="cheese" id="no" value="yes">
                <label for="no">No</label>
            </section>
            <hr>

            <section class="bun-type">
                <label for="bun">What type of bun would you like?</label>
                <select name="bun" id="bun">
                    <option value="sesame">Sesame</option>
                    <option value="potatoe">Potato</option>
                    <option value="pretzel">Pretzel</option>
                </select>
            </section>
            <hr>

            <section class="sauce-selection">
                <label for="sauce">What type of sauce would you like?</label>
                <input list="sauces" id="sauce" name="sauce">
                <datalist id="sauces">
                    <option value="ketchup"></option>
                    <option value="mayo"></option>
                    <option value="mustard"></option>
                </datalist>
            </section>
            <hr>
            <section class="extra-info">
                <label for="extra">Anything else you want to add?</label>
                <br>
                <textarea id="extra" name="extra" rows="3" cols="40"></textarea>
            </section>
            <hr>

            <section class="submission">
                <input type="submit" value="Submit" asp-page ="./Submission">
            </section>
        </form>
    </section>
</body>
</html>

Your New Favorite Poem/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<head>
    <title>Your New Favorite Poem</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <section class="text-center" id="Banner">
        <h1 class="display-2">Welcome to Your New Favorite Poem</h1>


        <p>
            This website is a place to discover new poets, the type of poets you wouldn't necessarily find in your English class.
            They're worthy of a look and especially worthy of supporting.
        </p>
        <p>You can find the source code <a href="https://gitlab.com/MetzinAround/Your-New-Favorite-Poem" target="_blank">here!</a></p>

    </section>


    <div class="buttonmove">
        <form method="post" asp-page="Index">
            <input class="button" type="submit" value="Read Random Poem" asp-page-handler="RandomPoem" formtarget="_blank" />
        </form>
    </div>
    <!--Index page as a single foreach loop-->

    @foreach (var author in @Model.AuthorsFromDatabase.Where(x => x.IsVerified is true))
    {   
        //poems and links not displaying after reseeding database
        <section class="poets">
            <h2>@author.Name </h2>
            <br/>
            <ul>
                @foreach (var poem in author.Poems.Where(x => x.IsVerified is true))
                {

                    <li><a id="@author.Name"href=@poem.URL target="_blank">@poem.Title</a></li>
                }
            </ul>
        </section>


        <section class="authorPicture">
            <img src=@author.PictureURL alt-text= @author.PictureAltText />
        </section>
    }
</body>

Your New Favorite Poem/Pages/Poets.cshtml
@page
@model Your_New_Favorite_Poem.Pages.PoetsModel
@{
    ViewData["Title"] = "Poets";
}
<head>
    <title>Poets</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <p> List of all currently featured poets on the page! </p>
    <nav>
        <!-- fullist of poets-->
        <ul>
            @foreach (var authorName in Model.AuthorsFromDatabase.Where(x => x.IsVerified).Select(x => x.Name).Distinct())
            {

                <li><a asp-area="" asp-page="/Index" asp-fragment=@authorName>@authorName</a></li>

            }
        </ul>
    </nav>
</body>

Your New Favorite Poem/Pages/Submission.cshtml
@page
@model Your_New_Favorite_Poem.Pages.SubmissionModel
@{
    ViewData["Title"] = "Submission";
}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <title>Forms Review</title>
</head>
<body>
    <section id="overlay">
        <img src="https://s3.amazonaws.com/codecademy-content/courses/web-101/unit-6/htmlcss1-img_burger-logo.svg" alt="Davie's Burgers Logo" id="logo">
        <hr>
        <h1>Thanks for your submission!</h1>
        <img id="burger" src="https://s3.amazonaws.com/codecademy-content/courses/learn-html-forms/burger.svg" alt="finished burger">
    </section>
</body>
</html>